### ISSUE TITLE
扫描不work

### ISSUE THREAD

**Issue by sevck** [JE2Se/AssetScan#3]
sevck@MacBook-Pro  ~/git-project/AssetScan   master  python3 AssetScan.py -i 114.55.253.62
    _                 _   ____
   / \   ___ ___  ___| |_/ ___|  ___ __ _ _ __
  / _ \ / __/ __|/ _ \ __\___ \ / __/ _` | '_ \
 / ___ \\__ \__ \  __/ |_ ___) | (_| (_| | | | |
/_/   \_\___/___/\___|\__|____/ \___\__,_|_| |_|

				Power by JE2Se   V1.2

	~请输入 -h 获取命令帮助~

正在对目标地址进行存活检测~~
    _                 _   ____
   / \   ___ ___  ___| |_/ ___|  ___ __ _ _ __
  / _ \ / __/ __|/ _ \ __\___ \ / __/ _` | '_ \
 / ___ \\__ \__ \  __/ |_ ___) | (_| (_| | | | |
/_/   \_\___/___/\___|\__|____/ \___\__,_|_| |_|

请选择存活探测的方式~
(1)Ping探测~(适用于内网内没有禁用Ping)
(2)ARP探测~（适用于内网内禁用Pin探测,不能跨网段)

    任意键退出程序~

请选择探测存活方式->1
存活地址已成功写入alive.txt中

    _                 _   ____
   / \   ___ ___  ___| |_/ ___|  ___ __ _ _ __
  / _ \ / __/ __|/ _ \ __\___ \ / __/ _` | '_ \
 / ___ \\__ \__ \  __/ |_ ___) | (_| (_| | | | |
/_/   \_\___/___/\___|\__|____/ \___\__,_|_| |_|

请选择端口扫描的方式~
(1)风险端口探测 (Socket方式,适用于少IP)
(2)风险端口探测 (Masscan方式,适用于多IP)
(3)常规端口探测 (Nmap方式,Nmap的top1000端口)
(4)全端口探测   (Socket方式,适用于少IP，准确率高)
(5)全端口探测   (Masscan方式,适用于多IP,存在误报率)

    任意键退出程序,并生成当前进度报告~

请填写扫描方式->3
正在目标常用端口进行探测扫描~~

    _                 _   ____
   / \   ___ ___  ___| |_/ ___|  ___ __ _ _ __
  / _ \ / __/ __|/ _ \ __\___ \ / __/ _` | '_ \
 / ___ \\__ \__ \  __/ |_ ___) | (_| (_| | | | |
/_/   \_\___/___/\___|\__|____/ \___\__,_|_| |_|

是否进行风险端口漏洞探测~
(1)探测风险端口

    任意键退出程序，并生成当前进度报告~

请选择是否进行漏洞探测->1
正在生成报告~
生成报告成功~
报告地址:./report/AssetScan_201912416494.docx
扫描结束~
 sevck@MacBook-Pro  ~/git-project/AssetScan   master 

**Comment by sevck** [comment]
默认不选择 崩溃
 ✘ sevck@MacBook-Pro  ~/git-project/AssetScan   master  python3 AssetScan.py -i 121.42.182.208
    _                 _   ____
   / \   ___ ___  ___| |_/ ___|  ___ __ _ _ __
  / _ \ / __/ __|/ _ \ __\___ \ / __/ _` | '_ \
 / ___ \\__ \__ \  __/ |_ ___) | (_| (_| | | | |
/_/   \_\___/___/\___|\__|____/ \___\__,_|_| |_|


				Power by JE2Se   V1.2

	~请输入 -h 获取命令帮助~

正在对目标地址进行存活检测~~
    _                 _   ____
   / \   ___ ___  ___| |_/ ___|  ___ __ _ _ __
  / _ \ / __/ __|/ _ \ __\___ \ / __/ _` | '_ \
 / ___ \\__ \__ \  __/ |_ ___) | (_| (_| | | | |
/_/   \_\___/___/\___|\__|____/ \___\__,_|_| |_|


请选择存活探测的方式~
(1)Ping探测~(适用于内网内没有禁用Ping)
(2)ARP探测~（适用于内网内禁用Pin探测,不能跨网段)

    任意键退出程序~


请选择探测存活方式->
存活地址已成功写入alive.txt中


Traceback (most recent call last):
  File "AssetScan.py", line 177, in <module>
    father(iplist)
  File "AssetScan.py", line 70, in father
    ipdata = open("./file/alive.txt","r")
FileNotFoundError: [Errno 2] No such file or directory: './file/alive.txt'

**Comment by JE2Se** [comment]
好的  感谢反馈，马上处理

**Comment by sevck** [comment]
CIDR IP报错。。 
sevck@MacBook-Pro  ~/git-project/AssetScan   master  python3 AssetScan.py -i 121.42.182.1/24
    _                 _   ____
   / \   ___ ___  ___| |_/ ___|  ___ __ _ _ __
  / _ \ / __/ __|/ _ \ __\___ \ / __/ _` | '_ \
 / ___ \\__ \__ \  __/ |_ ___) | (_| (_| | | | |
/_/   \_\___/___/\___|\__|____/ \___\__,_|_| |_|


				Power by JE2Se   V1.2

	~请输入 -h 获取命令帮助~

Traceback (most recent call last):
  File "AssetScan.py", line 176, in <module>
    iplist = IPinfo(ip)
  File "/Users/sevck/git-project/AssetScan/lib/iplist.py", line 79, in IPinfo
    IPauto(info)
  File "/Users/sevck/git-project/AssetScan/lib/iplist.py", line 16, in IPauto
    ipr = IP(ipl)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPy.py", line 260, in __init__
    raise ValueError("%s has invalid prefix length (%s)" % (repr(self), self._prefixlen))
ValueError: IP('121.42.182.1/24') has invalid prefix length (24)

**Comment by JE2Se** [comment]
感谢提BUG，已修复

**Comment by sevck** [comment]
![image](https://user-images.githubusercontent.com/11308052/70198700-7ec3c780-174a-11ea-9d0c-e3f14a5a8a04.png)
不能运行

**Comment by sevck** [comment]
代码锁紧写错了。。

**Comment by sevck** [comment]
![image](https://user-images.githubusercontent.com/11308052/70198796-d4986f80-174a-11ea-8724-2a54f12f44c8.png)
依旧不work

**Comment by sevck** [comment]
![image](https://user-images.githubusercontent.com/11308052/70198824-f1cd3e00-174a-11ea-86a5-882309fbb21e.png)
机器禁ping,arp无表，那不会扫么。。 端口也识别不出来，scan也不扫描，直接出报告

**Comment by JE2Se** [comment]
目前的话，你要扫网段的话，暂时还不支持192.168.1.1/24格式，今支持192.168.1.0/24
缩进已更改，感谢
分享一下设计想发，程序仅第一次存活检测异常会退出程序，接下来的风险端口检测，端口开放检测如果存活检测不管你输入什么选项都会执行，出报告，设计场景为，如果我只想检测存活，不探测漏洞，我可以在检测存活后，输入任意键，非1或2直接生成报告，但是如果你alive.py没有报错，但是没有扫描出存活的地址到alive.txt,那么其余的徐香都会赋值默认值，导致出报告，
工具的核心，如果你扫描不出存活，其他的都无法工作，会赋值默认值，出报告，
当前仅支持ping，arp，如果你禁ping，禁arp，程序暂时无法继续工作。

**Comment by devsecops-SRC** [comment]
大佬微信  只检测口令 不检测其他漏洞

**Comment by devsecops-SRC** [comment]
![image](https://user-images.githubusercontent.com/50866822/70229146-97ef6700-1790-11ea-8733-cbf5139fb8e7.png)

**Comment by JE2Se** [comment]
检测其他漏洞，只不过不存在罢了

**Comment by devsecops-SRC** [comment]
存在漏洞  没有检测出来  redis  mogodb等等

**Comment by JE2Se** [comment]
redis跟mongo目前只针对未授权测试。其他的没有检测，后期回增加

**Comment by WMdoit** [comment]
win10电脑需要另外安装masscan和nmap吗？
